name: PR Summary Generator
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create package.json
        run: |
          echo '{"type": "module"}' > package.json

      - name: Install dependencies
        run: npm install openai@^4.0.0

      - name: Generate and Post Summary
        uses: actions/github-script@v7
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          script: |
            const { generateSummary } = await import('./.github/scripts/generate-summary.js');
            
            const diff = await exec.getExecOutput('git diff origin/main...HEAD', [], {
              silent: true
            });

            if (!diff.stdout.trim()) {
              console.log('No changes detected in the PR');
              return;
            }

            await generateSummary(diff.stdout, process.env.OPENAI_API_KEY, github, context);